apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: kovendhan-portfolio
spec:
  template:
    spec:
      containers:
        - image: docker.io/kovendhan5/kovendhan-portflio:latest
          ports:
            - containerPort: 80
