steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/portfolio:latest'
      - '.'
    
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/portfolio:latest']
    
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'portfolio'
      - '--image=gcr.io/$PROJECT_ID/portfolio:latest'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=128Mi'
      - '--cpu=1'
      - '--port=80'
      - '--min-instances=0'
      - '--max-instances=1'
      
images:
  - 'gcr.io/$PROJECT_ID/portfolio:latest'

options:
  machineType: 'E2_MEDIUM'
