steps:
  # Build the container image with optimal caching
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--cache-from=gcr.io/$PROJECT_ID/portfolio:latest'
      - '--build-arg=COMMIT_SHA=$COMMIT_SHA'
      - '--build-arg=BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")'
      - '-t'
      - 'gcr.io/$PROJECT_ID/portfolio:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/portfolio:latest'
      - '.'
    
  # Push the container images to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/portfolio:$COMMIT_SHA']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/portfolio:latest']
    
  # Deploy container image to Cloud Run with minimal settings for testing
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'portfolio'
      - '--image=gcr.io/$PROJECT_ID/portfolio:$COMMIT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=256Mi'
      - '--cpu=1'
      - '--timeout=30s'
      - '--concurrency=10'
      - '--min-instances=0'
      - '--max-instances=2'
      - '--set-env-vars=COMMIT_SHA=$COMMIT_SHA,BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")'
      
images:
  - 'gcr.io/$PROJECT_ID/portfolio:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/portfolio:latest'

options:
  machineType: 'E2_MEDIUM'
  logging: CLOUD_LOGGING_ONLY
