apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: kovendhan-portfolio
spec:
  template:
    spec:
      serviceAccountName: portfolio-run-sa
      containers:
        - image: REGION-docker.pkg.dev/PROJECT_ID/kovendhan-portfolio/portfolio:latest
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
